### ISSUE TITLE
SSH agent support

### ISSUE THREAD

**Issue by kaithar** [sqlectron/sqlectron-db-core#15]
I'm not sure why agent support isn't popular in database clients but, at least in this case, it looks like adding it should be an easy job for someone familiar with the project.

If I'm reading correctly, you'd want to add to the configTunnel method: https://github.com/sqlectron/sqlectron-core/blob/master/src/db/tunnel.js#L73

Using this argument:

> agent - string - Path to ssh-agent's UNIX socket for ssh-agent-based user authentication. Windows users: set to 'pageant' for authenticating with Pageant or (actual) path to a cygwin "UNIX socket." Default: (none)

per mscdex/ssh2

... and then do all the UI hook up that I expect will actually take the time.

**Comment by maxclaus** [comment]
I had implemented agent support as a first attempt to fix https://github.com/sqlectron/sqlectron-db-core/pull/25. But, went back and solved the issue with direct private key instead. Since, there is interest on this feature I am gonna add support for this after that PR is merged.
